# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    tls:
      strict_transport_security:
          enabled: true
          include_subdomains: true
          preload: true
"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
"http://www.{default}/":
    type: redirect
    to: "https://{default}/"
"http://{default}/":
    type: redirect
    to: "https://{default}/"
